// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt50R-27AGXz0bE4YRGNVC7dy7jXY-Jyw',
    appId: '1:292409766433:android:5868034fcd78d7b46a6960',
    messagingSenderId: '292409766433',
    projectId: 'medigo-1e8f1',
    storageBucket: 'medigo-1e8f1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABCWcgxf1TqvN0cAHZRZHJ_btNclaQ7tI',
    appId: '1:292409766433:ios:6d851e292631978f6a6960',
    messagingSenderId: '292409766433',
    projectId: 'medigo-1e8f1',
    storageBucket: 'medigo-1e8f1.firebasestorage.app',
    iosBundleId: 'com.example.medigo',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyComuRmFnAJHmPgQsXKZsI6ZPd3C_p5194',
    appId: '1:292409766433:web:621fd462096b7d8c6a6960',
    messagingSenderId: '292409766433',
    projectId: 'medigo-1e8f1',
    authDomain: 'medigo-1e8f1.firebaseapp.com',
    storageBucket: 'medigo-1e8f1.firebasestorage.app',
    measurementId: 'G-TXBCDXPY91',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABCWcgxf1TqvN0cAHZRZHJ_btNclaQ7tI',
    appId: '1:292409766433:ios:6d851e292631978f6a6960',
    messagingSenderId: '292409766433',
    projectId: 'medigo-1e8f1',
    storageBucket: 'medigo-1e8f1.firebasestorage.app',
    iosBundleId: 'com.example.medigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyComuRmFnAJHmPgQsXKZsI6ZPd3C_p5194',
    appId: '1:292409766433:web:f9f74b88aadcb1f96a6960',
    messagingSenderId: '292409766433',
    projectId: 'medigo-1e8f1',
    authDomain: 'medigo-1e8f1.firebaseapp.com',
    storageBucket: 'medigo-1e8f1.firebasestorage.app',
    measurementId: 'G-6H0SJ0X3D5',
  );
}
